version: "3.8"

services:
  classification-app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: classification_app
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./notebooks:/app/notebooks
    restart: unless-stopped
